### ISSUE TITLE
Can display aliases instead of filenames on the backlink tab and outlink tab?

### ISSUE THREAD

**Issue by shaopeng1993** [basham/obsidian-alias-from-heading#5]
e.g.
![image](https://user-images.githubusercontent.com/128011119/228149774-4fc01531-60f5-433e-b228-f771d61e18e5.png)

**Comment by basham** [comment]
Unfortunately, this feature is not likely to be supported unless Obsidian publishes new developer APIs. Until v1.0.11, this plugin [modified the metadataCache](https://github.com/basham/obsidian-alias-from-heading/blob/1.0.11/main.ts#L203) to make aliases more available throughout Obsidian. It may have resolved your issue, but I can't recall. In order to get this plugin accepted in the plugin registry, I needed to [change that approach](https://github.com/obsidianmd/obsidian-releases/pull/1004#issuecomment-1180830178). As a result, the v1.0.12 plugin is a bit more limited than what it could be, but it means that it is less likely to cause unforeseen conflicts with other parts of Obsidian or other plugins.

I wish I had a better answer for you. But in glancing through the latest [dev documentation](https://docs.obsidian.md/), I'm not noticing anything that would help me get progress on this issue.

I'm open to ideas, if you have them.

**Comment by basham** [comment]
This is resolved as of v1.1. Thanks for posting the issue!
